from unittest.mock import patch

import pytest
from pyaudio import PyAudio

from audio import VbCableIn, VbCableOut, NoCableFound, get_cable

AUDIO_DEVICES = [
    {
        "index": 0,
        "name": "Microsoft Sound Mapper - Input",
        "hostApi": 0,
        "maxInputChannels": 2,
        "maxOutputChannels": 0,
        "defaultLowInputLatency": 0.09,
        "defaultLowOutputLatency": 0.09,
        "defaultHighInputLatency": 0.18,
        "defaultHighOutputLatency": 0.18,
        "defaultSampleRate": 44100.0,
    },
    {
        "index": 1,
        "name": "CABLE-B Output (VB-Audio Cable ",
        "hostApi": 0,
        "maxInputChannels": 8,
        "maxOutputChannels": 0,
        "defaultLowInputLatency": 0.09,
        "defaultLowOutputLatency": 0.09,
        "defaultHighInputLatency": 0.18,
        "defaultHighOutputLatency": 0.18,
        "defaultSampleRate": 44100.0,
    },
    {
        "index": 2,
        "name": "CABLE Output (VB-Audio Virtual ",
        "hostApi": 0,
        "maxInputChannels": 8,
        "maxOutputChannels": 0,
        "defaultLowInputLatency": 0.09,
        "defaultLowOutputLatency": 0.09,
        "defaultHighInputLatency": 0.18,
        "defaultHighOutputLatency": 0.18,
        "defaultSampleRate": 44100.0,
    },
    {
        "index": 3,
        "name": "CABLE-A Output (VB-Audio Cable ",
        "hostApi": 0,
        "maxInputChannels": 8,
        "maxOutputChannels": 0,
        "defaultLowInputLatency": 0.09,
        "defaultLowOutputLatency": 0.09,
        "defaultHighInputLatency": 0.18,
        "defaultHighOutputLatency": 0.18,
        "defaultSampleRate": 44100.0,
    },
    {
        "index": 4,
        "name": "Microsoft Sound Mapper - Output",
        "hostApi": 0,
        "maxInputChannels": 0,
        "maxOutputChannels": 2,
        "defaultLowInputLatency": 0.09,
        "defaultLowOutputLatency": 0.09,
        "defaultHighInputLatency": 0.18,
        "defaultHighOutputLatency": 0.18,
        "defaultSampleRate": 44100.0,
    },
    {
        "index": 5,
        "name": "Realtek Digital Output (Realtek",
        "hostApi": 0,
        "maxInputChannels": 0,
        "maxOutputChannels": 2,
        "defaultLowInputLatency": 0.09,
        "defaultLowOutputLatency": 0.09,
        "defaultHighInputLatency": 0.18,
        "defaultHighOutputLatency": 0.18,
        "defaultSampleRate": 44100.0,
    },
    {
        "index": 6,
        "name": "CABLE-A Input (VB-Audio Cable A",
        "hostApi": 0,
        "maxInputChannels": 0,
        "maxOutputChannels": 8,
        "defaultLowInputLatency": 0.09,
        "defaultLowOutputLatency": 0.09,
        "defaultHighInputLatency": 0.18,
        "defaultHighOutputLatency": 0.18,
        "defaultSampleRate": 44100.0,
    },
    {
        "index": 7,
        "name": "CABLE-B Input (VB-Audio Cable B",
        "hostApi": 0,
        "maxInputChannels": 0,
        "maxOutputChannels": 8,
        "defaultLowInputLatency": 0.09,
        "defaultLowOutputLatency": 0.09,
        "defaultHighInputLatency": 0.18,
        "defaultHighOutputLatency": 0.18,
        "defaultSampleRate": 44100.0,
    },
    {
        "index": 8,
        "name": "CABLE Input (VB-Audio Virtual C",
        "hostApi": 0,
        "maxInputChannels": 0,
        "maxOutputChannels": 8,
        "defaultLowInputLatency": 0.09,
        "defaultLowOutputLatency": 0.09,
        "defaultHighInputLatency": 0.18,
        "defaultHighOutputLatency": 0.18,
        "defaultSampleRate": 44100.0,
    },
    {
        "index": 9,
        "name": "Primary Sound Capture Driver",
        "hostApi": 1,
        "maxInputChannels": 2,
        "maxOutputChannels": 0,
        "defaultLowInputLatency": 0.12,
        "defaultLowOutputLatency": 0.0,
        "defaultHighInputLatency": 0.24,
        "defaultHighOutputLatency": 0.0,
        "defaultSampleRate": 44100.0,
    },
    {
        "index": 10,
        "name": "CABLE-B Output (VB-Audio Cable B)",
        "hostApi": 1,
        "maxInputChannels": 8,
        "maxOutputChannels": 0,
        "defaultLowInputLatency": 0.12,
        "defaultLowOutputLatency": 0.0,
        "defaultHighInputLatency": 0.24,
        "defaultHighOutputLatency": 0.0,
        "defaultSampleRate": 44100.0,
    },
    {
        "index": 11,
        "name": "CABLE Output (VB-Audio Virtual Cable)",
        "hostApi": 1,
        "maxInputChannels": 8,
        "maxOutputChannels": 0,
        "defaultLowInputLatency": 0.12,
        "defaultLowOutputLatency": 0.0,
        "defaultHighInputLatency": 0.24,
        "defaultHighOutputLatency": 0.0,
        "defaultSampleRate": 44100.0,
    },
    {
        "index": 12,
        "name": "CABLE-A Output (VB-Audio Cable A)",
        "hostApi": 1,
        "maxInputChannels": 8,
        "maxOutputChannels": 0,
        "defaultLowInputLatency": 0.12,
        "defaultLowOutputLatency": 0.0,
        "defaultHighInputLatency": 0.24,
        "defaultHighOutputLatency": 0.0,
        "defaultSampleRate": 44100.0,
    },
    {
        "index": 13,
        "name": "Primary Sound Driver",
        "hostApi": 1,
        "maxInputChannels": 0,
        "maxOutputChannels": 2,
        "defaultLowInputLatency": 0.0,
        "defaultLowOutputLatency": 0.12,
        "defaultHighInputLatency": 0.0,
        "defaultHighOutputLatency": 0.24,
        "defaultSampleRate": 44100.0,
    },
    {
        "index": 14,
        "name": "Realtek Digital Output (Realtek(R) Audio)",
        "hostApi": 1,
        "maxInputChannels": 0,
        "maxOutputChannels": 2,
        "defaultLowInputLatency": 0.0,
        "defaultLowOutputLatency": 0.12,
        "defaultHighInputLatency": 0.0,
        "defaultHighOutputLatency": 0.24,
        "defaultSampleRate": 44100.0,
    },
    {
        "index": 15,
        "name": "CABLE-A Input (VB-Audio Cable A)",
        "hostApi": 1,
        "maxInputChannels": 0,
        "maxOutputChannels": 8,
        "defaultLowInputLatency": 0.0,
        "defaultLowOutputLatency": 0.12,
        "defaultHighInputLatency": 0.0,
        "defaultHighOutputLatency": 0.24,
        "defaultSampleRate": 44100.0,
    },
    {
        "index": 16,
        "name": "CABLE-B Input (VB-Audio Cable B)",
        "hostApi": 1,
        "maxInputChannels": 0,
        "maxOutputChannels": 8,
        "defaultLowInputLatency": 0.0,
        "defaultLowOutputLatency": 0.12,
        "defaultHighInputLatency": 0.0,
        "defaultHighOutputLatency": 0.24,
        "defaultSampleRate": 44100.0,
    },
    {
        "index": 17,
        "name": "CABLE Input (VB-Audio Virtual Cable)",
        "hostApi": 1,
        "maxInputChannels": 0,
        "maxOutputChannels": 8,
        "defaultLowInputLatency": 0.0,
        "defaultLowOutputLatency": 0.12,
        "defaultHighInputLatency": 0.0,
        "defaultHighOutputLatency": 0.24,
        "defaultSampleRate": 44100.0,
    },
    {
        "index": 18,
        "name": "CABLE-A Input (VB-Audio Cable A)",
        "hostApi": 2,
        "maxInputChannels": 0,
        "maxOutputChannels": 2,
        "defaultLowInputLatency": 0.0,
        "defaultLowOutputLatency": 0.003,
        "defaultHighInputLatency": 0.0,
        "defaultHighOutputLatency": 0.01,
        "defaultSampleRate": 44100.0,
    },
    {
        "index": 19,
        "name": "CABLE-B Input (VB-Audio Cable B)",
        "hostApi": 2,
        "maxInputChannels": 0,
        "maxOutputChannels": 2,
        "defaultLowInputLatency": 0.0,
        "defaultLowOutputLatency": 0.003,
        "defaultHighInputLatency": 0.0,
        "defaultHighOutputLatency": 0.01,
        "defaultSampleRate": 44100.0,
    },
    {
        "index": 20,
        "name": "Realtek Digital Output (Realtek(R) Audio)",
        "hostApi": 2,
        "maxInputChannels": 0,
        "maxOutputChannels": 2,
        "defaultLowInputLatency": 0.0,
        "defaultLowOutputLatency": 0.003,
        "defaultHighInputLatency": 0.0,
        "defaultHighOutputLatency": 0.0101587,
        "defaultSampleRate": 44100.0,
    },
    {
        "index": 21,
        "name": "CABLE Input (VB-Audio Virtual Cable)",
        "hostApi": 2,
        "maxInputChannels": 0,
        "maxOutputChannels": 2,
        "defaultLowInputLatency": 0.0,
        "defaultLowOutputLatency": 0.003,
        "defaultHighInputLatency": 0.0,
        "defaultHighOutputLatency": 0.01,
        "defaultSampleRate": 192000.0,
    },
    {
        "index": 22,
        "name": "CABLE Output (VB-Audio Virtual Cable)",
        "hostApi": 2,
        "maxInputChannels": 2,
        "maxOutputChannels": 0,
        "defaultLowInputLatency": 0.003,
        "defaultLowOutputLatency": 0.0,
        "defaultHighInputLatency": 0.01,
        "defaultHighOutputLatency": 0.0,
        "defaultSampleRate": 44100.0,
    },
    {
        "index": 23,
        "name": "CABLE-B Output (VB-Audio Cable B)",
        "hostApi": 2,
        "maxInputChannels": 2,
        "maxOutputChannels": 0,
        "defaultLowInputLatency": 0.003,
        "defaultLowOutputLatency": 0.0,
        "defaultHighInputLatency": 0.01,
        "defaultHighOutputLatency": 0.0,
        "defaultSampleRate": 44100.0,
    },
    {
        "index": 24,
        "name": "CABLE-A Output (VB-Audio Cable A)",
        "hostApi": 2,
        "maxInputChannels": 2,
        "maxOutputChannels": 0,
        "defaultLowInputLatency": 0.003,
        "defaultLowOutputLatency": 0.0,
        "defaultHighInputLatency": 0.01,
        "defaultHighOutputLatency": 0.0,
        "defaultSampleRate": 44100.0,
    },
    {
        "index": 25,
        "name": "CABLE-A Output (VB-Audio CABLE-A)",
        "hostApi": 3,
        "maxInputChannels": 8,
        "maxOutputChannels": 0,
        "defaultLowInputLatency": 0.01,
        "defaultLowOutputLatency": 0.01,
        "defaultHighInputLatency": 0.0853,
        "defaultHighOutputLatency": 0.0853,
        "defaultSampleRate": 44100.0,
    },
    {
        "index": 26,
        "name": "Speakers (VB-Audio CABLE-A)",
        "hostApi": 3,
        "maxInputChannels": 0,
        "maxOutputChannels": 8,
        "defaultLowInputLatency": 0.01,
        "defaultLowOutputLatency": 0.01,
        "defaultHighInputLatency": 0.0853,
        "defaultHighOutputLatency": 0.0853,
        "defaultSampleRate": 44100.0,
    },
    {
        "index": 27,
        "name": "Headphones (Realtek HD Audio 2nd output)",
        "hostApi": 3,
        "maxInputChannels": 0,
        "maxOutputChannels": 2,
        "defaultLowInputLatency": 0.01,
        "defaultLowOutputLatency": 0.01,
        "defaultHighInputLatency": 0.04,
        "defaultHighOutputLatency": 0.04,
        "defaultSampleRate": 44100.0,
    },
    {
        "index": 28,
        "name": "Stereo Mix (Realtek HD Audio Stereo input)",
        "hostApi": 3,
        "maxInputChannels": 2,
        "maxOutputChannels": 0,
        "defaultLowInputLatency": 0.01,
        "defaultLowOutputLatency": 0.01,
        "defaultHighInputLatency": 0.04,
        "defaultHighOutputLatency": 0.04,
        "defaultSampleRate": 48000.0,
    },
    {
        "index": 29,
        "name": "Microphone (Realtek HD Audio Mic input)",
        "hostApi": 3,
        "maxInputChannels": 2,
        "maxOutputChannels": 0,
        "defaultLowInputLatency": 0.01,
        "defaultLowOutputLatency": 0.01,
        "defaultHighInputLatency": 0.04,
        "defaultHighOutputLatency": 0.04,
        "defaultSampleRate": 44100.0,
    },
    {
        "index": 30,
        "name": "Speakers (Realtek HDA Primary output)",
        "hostApi": 3,
        "maxInputChannels": 0,
        "maxOutputChannels": 8,
        "defaultLowInputLatency": 0.01,
        "defaultLowOutputLatency": 0.01,
        "defaultHighInputLatency": 0.04,
        "defaultHighOutputLatency": 0.04,
        "defaultSampleRate": 44100.0,
    },
    {
        "index": 31,
        "name": "SPDIF Out (Realtek HDA SPDIF Out)",
        "hostApi": 3,
        "maxInputChannels": 0,
        "maxOutputChannels": 2,
        "defaultLowInputLatency": 0.01,
        "defaultLowOutputLatency": 0.01,
        "defaultHighInputLatency": 0.04,
        "defaultHighOutputLatency": 0.04,
        "defaultSampleRate": 44100.0,
    },
    {
        "index": 32,
        "name": "CABLE-B Output (VB-Audio CABLE-B)",
        "hostApi": 3,
        "maxInputChannels": 8,
        "maxOutputChannels": 0,
        "defaultLowInputLatency": 0.01,
        "defaultLowOutputLatency": 0.01,
        "defaultHighInputLatency": 0.0853,
        "defaultHighOutputLatency": 0.0853,
        "defaultSampleRate": 44100.0,
    },
    {
        "index": 3,
        "name": "Speakers (VB-Audio CABLE-B)",
        "hostApi": 3,
        "maxInputChannels": 0,
        "maxOutputChannels": 8,
        "defaultLowInputLatency": 0.01,
        "defaultLowOutputLatency": 0.01,
        "defaultHighInputLatency": 0.0853,
        "defaultHighOutputLatency": 0.0853,
        "defaultSampleRate": 44100.0,
    },
    {
        "index": 34,
        "name": "CABLE Output (VB-Audio Point)",
        "hostApi": 3,
        "maxInputChannels": 8,
        "maxOutputChannels": 0,
        "defaultLowInputLatency": 0.01,
        "defaultLowOutputLatency": 0.01,
        "defaultHighInputLatency": 0.0853,
        "defaultHighOutputLatency": 0.0853,
        "defaultSampleRate": 44100.0,
    },
    {
        "index": 35,
        "name": "Speakers (VB-Audio Point)",
        "hostApi": 3,
        "maxInputChannels": 0,
        "maxOutputChannels": 8,
        "defaultLowInputLatency": 0.01,
        "defaultLowOutputLatency": 0.01,
        "defaultHighInputLatency": 0.0853,
        "defaultHighOutputLatency": 0.0853,
        "defaultSampleRate": 44100.0,
    },
]


@pytest.mark.parametrize(
    "cable, expected_id",
    [
        pytest.param(VbCableIn.CABLE_INPUT, 8, id="default-cable-in"),
        pytest.param(VbCableIn.CABLE_A_INPUT, 6, id="a-cable-in"),
        pytest.param(VbCableIn.CABLE_B_INPUT, 7, id="b-cable-in"),
        pytest.param(VbCableIn.CABLE_C_INPUT, -1, id="c-cable-in"),
        pytest.param(VbCableIn.CABLE_D_INPUT, -1, id="d-cable-in"),
        pytest.param(VbCableOut.CABLE_OUTPUT, 2, id="default-cable-out"),
        pytest.param(VbCableOut.CABLE_A_OUTPUT, 3, id="a-cable-out"),
        pytest.param(VbCableOut.CABLE_B_OUTPUT, 1, id="b-cable-out"),
        pytest.param(VbCableOut.CABLE_C_OUTPUT, -1, id="c-cable-out"),
        pytest.param(VbCableOut.CABLE_D_OUTPUT, -1, id="d-cable-out"),
    ],
)
def test_get_cable(cable: VbCableIn | VbCableOut, expected_id: int):
    with patch.object(PyAudio, "get_device_count", return_value=len(AUDIO_DEVICES)):
        with patch.object(PyAudio, "get_device_info_by_index", lambda self, x: AUDIO_DEVICES[x]):
            if expected_id == -1:
                with pytest.raises(NoCableFound):
                    get_cable(cable)
            else:
                actual_cable = get_cable(cable)
                assert actual_cable == AUDIO_DEVICES[expected_id]
